const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('widget', {
  getUpdateState: () => ipcRenderer.invoke('updates:get'),
  checkForUpdates: () => ipcRenderer.invoke('updates:check'),
  downloadUpdate: () => ipcRenderer.invoke('updates:download'),
  installUpdate: () => ipcRenderer.invoke('updates:install'),
  onUpdateState: (cb) => ipcRenderer.on('updates:state', (_e, state) => cb(state)),
  onOpenUpdates: (cb) => ipcRenderer.on('updates:open', cb),
  getUsage: () => ipcRenderer.invoke('usage:get'),
  getStore: () => ipcRenderer.invoke('store:get'),
  setStore: (patch) => ipcRenderer.invoke('store:set', patch),
  selectCompanion: (data) => ipcRenderer.invoke('companions:select', data),
  setTokenTarget: (data) => ipcRenderer.invoke('companions:target', data),
  onCompanions: (cb) => ipcRenderer.on('companions:update', (_e, state) => cb(state)),
  notificationState: () => ipcRenderer.invoke('notifications:state'),
  setNotificationPreferences: (patch) => ipcRenderer.invoke('notifications:preferences:set', patch),
  saveTelegramCredentials: (data) => ipcRenderer.invoke('notifications:telegram:save', data),
  findTelegramChat: () => ipcRenderer.invoke('notifications:telegram:find-chat'),
  connectKakao: (data) => ipcRenderer.invoke('notifications:kakao:connect', data),
  disconnectKakao: () => ipcRenderer.invoke('notifications:kakao:disconnect'),
  testNotification: () => ipcRenderer.invoke('notifications:test'),
  installNotificationHooks: () => ipcRenderer.invoke('notifications:hooks:install'),
  removeNotificationHooks: () => ipcRenderer.invoke('notifications:hooks:remove'),
  claudeLogin: () => ipcRenderer.invoke('claude:login'),
  openUrl: (url) => ipcRenderer.invoke('open:url', url),
  hide: () => ipcRenderer.invoke('win:hide'),
  setOpacity: (v) => ipcRenderer.invoke('win:opacity', v),
  fitSize: (w, h, anchor) => ipcRenderer.invoke('win:fitSize', w, h, anchor),
  setZoom: (z) => ipcRenderer.invoke('win:zoom', z),
  onNear: (cb) => ipcRenderer.on('near', (_e, v) => cb(v)),
  onMode: (cb) => ipcRenderer.on('mode', (_e, mode) => cb(mode)),
  autostart: (on) => ipcRenderer.invoke('app:autostart', on),
  onRefresh: (cb) => ipcRenderer.on('refresh-now', cb),
  onNotificationStatus: (cb) => ipcRenderer.on('notify:status', (_e, status) => cb(status)),
  setTrayLabels: (labels) => ipcRenderer.invoke('tray:labels', labels),
  notify: (title, body) => ipcRenderer.invoke('notify', title, body),
  setHotkeys: (hk) => ipcRenderer.invoke('hotkeys:set', hk),
  suspendHotkeys: () => ipcRenderer.invoke('hotkeys:suspend'),
  hotkeyStatus: () => ipcRenderer.invoke('hotkeys:status'),
  onHotkey: (cb) => ipcRenderer.on('hotkey', (_e, name, wasVisible) => cb(name, wasVisible)),
});
